### ISSUE TITLE
Chrome Exception

### ISSUE THREAD

**Issue by slammpete** [bellingcat/likee-downloader#3]
I tried running 

" likee_downloader -s username"

here is the output and error. i have de-googled version of chrome working on arch.

[INFO] Capturing profile screenshot: redacted
[INFO] Screenshot captured: downloads/screenshots/redacted_likee-downloader.png
[INFO] Obtaining userId...
[ERROR] Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16 

In your description you mentioned that i needed firefox installed, which i do. 

Thanks for any help.

btw i am running this version of chrome -

https://github.com/ungoogled-software/ungoogled-chromium

**Comment by rly0nheart** [comment]
Hello @slammpete, I had a look at that. That error occurs when an element was not found in the webpage. So I looked over the likee website, and it seems they have made changes to it. One will no longer view videos or profiles without an account.

**Comment by slammpete** [comment]
ah that is too bad. i really appreciate you getting back to me.

i will just go back to scraping picnob.com. the site lets you get full size
images and videos without an account.

**Comment by rly0nheart** [comment]
I will take a look at picnob too, sounds like something worth looking at. Thanks

**Comment by slammpete** [comment]
yes just try not to spread it around too much or it will get taken down.
it's the only site i know of that does not sensor posts and doesn't ban
your or blacklist you for downloading too much data.

another great sites specifically for searching tags is https://imgsed.com/
, with  a little url hacking it will let you look through the full results
of a particular tag. so if u really wanted to see all  100,000 posts with a
tag it will show them all to you. twitter does not allow u to do this and
cuts you the results off at a certain point.

but i ask that you keep these to yourself because if too many people start
using them twitter will have them taken down.

**Comment by slammpete** [comment]
this goes against what i believe in as i think all of this public info
should be available to all but i only asked u to keep it quit due to
selfish reasons.

if u were to go against my wishes and do something with these sites, i
won't hold it against you.

**Comment by rly0nheart** [comment]
Thanks these are good!. You should also check out https://picuki.com, it's for Instagram

**Comment by slammpete** [comment]
no problem,it took ages to find them though.

the site u sent has a nice interface but they don't give you the full sized
photos. plus if you scrape the site regularly the start to block your ip's.

right now i have 15 tabs of picnob open while also scraping two sites on
their site and they don't throttle or ban my ip's. i've been using the site
for a year and hit is hard almost everyday and never had a problem. the
only annoying this about scraping their site is that they require you to
manually interact and press on a button saying you want to see more. they
do it at every 100 photos or so. The only solution i have found is to use a
a script that auto scrolls down the site and then i have to click on the
button before doing a scrape.

if you can code around this that would be very helpful :)

**Comment by slammpete** [comment]
hey i found the ultimate one, everything works. tags, stories, etc.
functions like instagram but u cannot look at friend lists of the person
and it does not show the number of likes of posts. but other than that....

https://imgsed.com/

**Comment by rly0nheart** [comment]
I wrote a simple scraper for that. So far, it only manages to get the first 9 posts. I think it would be more useful if it gets all the posts

**Comment by rly0nheart** [comment]
Hey @slammpete, so I just found out that this program works well when you're in Russia. That measn you might want to use a VPN now.

**Comment by slammpete** [comment]
i am using mullvad vpn, i will give it a try. thanks.

**Comment by slammpete** [comment]
in order to get all the posts you need to  first click through the button
"See more" every 50 photos. i am just using the 'download all images app"
set to level 2.
