### ISSUE TITLE
Download is limited to 100 videos

### ISSUE THREAD

**Issue by NapInFever** [bellingcat/likee-downloader#7]
**Describe the bug**
If I put the -C argument with value 100, the download will still finish at 100 even if there are more videos. Is it possible to fix?

Thank you

**To Reproduce**
C:\Users\Alex>likee_downloader NastyaIskorka -c 200

    likee-downloader v1.6.0 Copyright (C) 2023  Richard Mwewa

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

[INFO] Obtaining userId...
[INFO] userId obtained: 1324842636
[FOUND] Found: 100 videos

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rly0nheart** [comment]
Hello again @NapInFever 😅, yeah so the 100 limit is not set by me actually. It's set by the API being used (in my opinion, it's a fair limit).

**Comment by NapInFever** [comment]
thank you very much, Richard!

**Comment by rly0nheart** [comment]
> thank you very much, Richard!

You should use the `-l` or `--limit` to specify the number of posts to get, the use the `-dl` or `--download` to download the videos (it will only return the video information by default).

Also, thank you for the coffee of By Me A Coffee!😊
